### ISSUE TITLE
Theme does not work on ghost.org

### ISSUE THREAD

**Issue by Zero3** [SuphanutJui/Material-Sidenav-Ghost-Theme#1]
Hi there :)

I like the theme! Unfortunately, https://github.com/SuphanutJui/Material-Sidenav-Ghost-Theme/archive/master.zip does not work when uploaded to https://ghost.org:

![image](https://cloud.githubusercontent.com/assets/82504/18479769/847cd2b2-79d6-11e6-9734-20ec6aab5f65.png)

Is there any chance that this theme will be made compatible with https://ghost.org? I found it via the marketplace at http://marketplace.ghost.org/.

**Comment by SuphanutJui** [comment]
Hi there,

I am so sorry that I don't really know what is the problem. I built this
theme for my own blog which is self-hosted, so it might not work with
Ghost(Pro). Also, I'm currently busy for examination.

Anyway, if I'm free, I will probably try to make it compatible with
ghost.org.

Thank you for you interest.

Suphanut

**Comment by Zero3** [comment]
Hiya!

No worries. I discovered that theme uploading is broken on ghost.org, and that this theme thus is not the cause of the error. The guys in their Slack is saying that it should be fixed soon. I will give your theme a try then, instead :). So apologies for this issue, which I will close again!

Good luck with your exams :).
